### ISSUE TITLE
output is stereo while the mic is mono

### ISSUE THREAD

**Issue by ildar** [dkim0419/SoundRecorder#22]
I think this is trivial to fix: the output is stereo with right channel mute. Should be mono as the input.
Thanks!

**Comment by fabianrost84** [comment]
Are the recorded files actually stereo files? Or are they mono files and it is just a playback issue?

On my Motorola Moto E recored files are mono and correctly played back.

**Comment by stsydow** [comment]
Yes it its. Just set in startRecording():
         mRecorder.setAudioChannels(1);

I started coding and have some huge changesets. 
It's not very maintenance friendly I'm sorry for that.

**Comment by andrewgaul** [comment]
I also see mono recordings with a Nexus 5x.

**Comment by fabianrost84** [comment]
Fixed by #36. Please close.
