### ISSUE TITLE
Future direction of the app

### ISSUE THREAD

**Issue by fabianrost84** [dkim0419/SoundRecorder#37]
Hi @dkim0419,
As there is a number of open Issues I was wondering what your future plans with the app are. Are you planning to develop it further? Are you interested in incorporating the suggested features or should this app remain simple without any settings? Do you see this app more as a Voice recorder (=focus on recording low quality, low size audio files) or as a Music recorder (=focus on recording high quality, bigger size files) or generic (=can do both things, settings needed).

I use it to record music in high quality using an external microphone. However, I needed to tweak it a little to fit to [my needs](https://github.com/fabianrost84/SoundRecorder). For me it's currently the best open source app available. I used to like Rehearsal Assistant, but that seems not to be developed any further.

**Comment by dkim0419** [comment]
Currently I am not actively developing the application further. I think I will keep the app to be a simple voice recorder rather than an application for music recording just to keep the simplicity.

**Comment by fabianrost84** [comment]
As people are still using the app it might be fair to state that it's currently not developed in the README.
