### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by moshpirit** [dkim0419/SoundRecorder#51]
It has been almost two years since the last update, and there's no moving here since January (you have a life, I'm not criticising it, quite the opposite, the app is great) but I think an update with what's already done would be nice.

**Comment by andrewgaul** [comment]
See #37.  I also would like to see a few pull requests merged and a new release as this is the best free software sound recorder I have found.

**Comment by moshpirit** [comment]
I didn't notice there were more pull requests around. Do you know if there's any fork? I'm not a developer but if I would, I'd continue at least the pull requests.

**Comment by andrewgaul** [comment]
Both @fabianrost84 and I have slightly diverged forks.  Personally I lack the motivation and skills to create a real fork and release and I prefer to work with upstream if possible.

**Comment by moshpirit** [comment]
Cool! If you create any apk, please let me know :)

**Comment by dkim0419** [comment]
Hey, thanks for the continued interest in the app! Really appreciate all the support I've been receiving but due to other time constraints I haven't been actively working on this project :(

**Comment by moshpirit** [comment]
Good to have you here! I think this is a really good chance for you to make a quick update, at least with the pull requests and create the last apk. We all appreciated that. 

We do understand that there's more life behind a (great) recorder, but this would be a cool favour. 

Sorry for the bother and thanks so much for all your work!!

**Comment by dkim0419** [comment]
Definitely. I'll take a look at the pull requests and barring no issues with testing will have an update out including them.

**Comment by dkim0419** [comment]
Hey, just merged the pull requests and pushed a new version to Google Play!
Thanks again for all the support :)

Just a personal preference matter - I opted to leave the default file naming scheme (My Recording #x) over the timestamp version.
