### ISSUE TITLE
Gradle is not syncing!

### ISSUE THREAD

**Issue by coolamz** [dkim0419/SoundRecorder#62]
I'm not able to sync Gradle. The error is Unknown host 'downloads.gradle.org' You may need to adjust proxy settings in Gradle. I'm not using any proxies. I've tried changing proxy settings to auto detect still, it didn't help.

**Comment by ildar** [comment]
This is your local problem. Please don't spoil it here and close the issue.

**Comment by coolamz** [comment]
Okay! I'll check. Sorry for misunderstanding.
