### ISSUE TITLE
copycat app with monetization

### ISSUE THREAD

**Issue by avipars** [dkim0419/SoundRecorder#66]
This one: https://play.google.com/store/apps/details?id=com.ssaurel.audiorecorder&hl=en

I don't know the internal workings with the MIT License, but this guy has copied several apps, just added advertisements and posted it to the play store.

**Comment by dkim0419** [comment]
oh wow, thanks for letting me know

**Comment by andrewgaul** [comment]
The MIT license allows this.  I left a negative review since the rip off app only adds advertisements.

**Comment by dkim0419** [comment]
thanks for that! sucks that he copied it but I didn't make this app with monetization in mind, which is why I left it open sourced and free.

**Comment by avipars** [comment]
Yep. In Israel, the saying is אין מה לעשות, meaning we can do nothing.
Thanks for checking out the thread!

**Comment by Poussinou** [comment]
Another one here: https://play.google.com/store/apps/details?id=com.okashaakmal.soundrecorder

**Comment by Poussinou** [comment]
Another one here: https://play.google.com/store/apps/details?id=com.diamond.apps.soundrecorder from [this developer](https://play.google.com/store/apps/dev?id=7637933278077959289)

EDIT: another one here https://play.google.com/store/apps/details?id=com.RedMoonStudio.HDsoundrecorder

**Comment by Poussinou** [comment]
https://play.google.com/store/apps/details?id=com.charli.soundrecorder.audiorecorder.voicerecording from [this developer](https://play.google.com/store/apps/developer?id=Charli)

**Comment by dbrgn** [comment]
Here's another one: https://play.google.com/store/apps/details?id=avinash42.soundrecorder Seems to be quite popular with over 100k installs.

No attribution is given, it thus violates the GPL license.

**Comment by Poussinou** [comment]
https://play.google.com/store/apps/details?id=com.ultron.soundrecorder from [this developer](https://play.google.com/store/apps/dev?id=9038274528328297818)

**Comment by Poussinou** [comment]
https://play.google.com/store/apps/details?id=com.droidfactory.audiorecorder.playereditor

**Comment by Poussinou** [comment]
https://play.google.com/store/apps/details?id=voice.recorder.voicerecorder from [this developer](https://play.google.com/store/apps/dev?id=6362486356489191167)

**Comment by Poussinou** [comment]
https://play.google.com/store/apps/details?id=arcturus.studio.soundrecorder from [this developer](https://play.google.com/store/apps/developer?id=Arcturus+Studio)

**Comment by Poussinou** [comment]
https://play.google.com/store/apps/details?id=com.atechnos.soundrecorders from [this developer](https://play.google.com/store/apps/developer?id=ATechnos+Utilites+Information)
