### ISSUE TITLE
Clone found

### ISSUE THREAD

**Issue by IzzySoft** [dkim0419/SoundRecorder#67]
Just in case you're not aware of, please take a look [here](https://github.com/DsignConcept/Recorder/blob/master/app/src/main/AndroidManifest.xml). Especially at the line stating the package name. Looks like it's a clone of your project, no credits given in its description. The clone is even available [at the playstore](https://play.google.com/store/apps/details?id=realrec.design.concept) – no credits there either.

**Comment by andrewgaul** [comment]
Similar to #66.

**Comment by frankyxcs** [comment]
This author here has also cloned this app from another github responsitory :) dkim0419 only rewrote this app a bit..so what is wrong and what is right.i have found the original app here on github some days ago. you you can blame everyone

**Comment by fabianrost84** [comment]
Where's the original one? Could you give a link @frankyxcs ? Not to blame, I'm just curious.

**Comment by frankyxcs** [comment]
Hi personally i hate it to blame anyone and i think everyone has to clean first this own door but if i see all the guys there blaming others ...:( This is only an easy recorder app nothing more.

https://github.com/MohammadAG/Android-SoundRecorder

So guys be carefull in the future with blaming others please ! :)

**Comment by IzzySoft** [comment]
@frankyxcs I do not blame anyone for *copying* – if I open-source my tools (which I do) I explicitly permit that or even invite to. It's rather the "not giving credits" I blame. And in the case I turned up, even the package name was kept unaltered, which points to a general carelessness.

So nothing about "forking" a project, that's all fine as long as credits are given. Even if the license doesn't explicitly state this, to me that's what decency calls for – rather than running around in borrowed plumes.

Instead of blaming anyone personally by contacting them, another fine idea would be to keep a list of "forks" and "pseudo-forks" – e.g. right on the main page (`README.md`). Along with the source of where the original project can be found, if one "forked" the project oneself :innocent:

**Comment by frankyxcs** [comment]
Hi  OK peace together :) But as you can see even dkim ist not clean :) So we should forget about this and he should close this thread. 
But you are right. It would be always nicer from people to give credits or if they change, improve the code etc. to mention maybe the original author.

**Comment by IzzySoft** [comment]
No war declared :stuck_out_tongue_winking_eye:

I was hoping for @dkim0419 to pick my hint, which would satisfy the issue both ways (up and down), and *then* close this issue. Maybe I'm just too idealistic, wanting to make the world a better place :innocent:

**Comment by dkim0419** [comment]
yep, i did use that project to learn especially how to use sql in android (both implementing the db and displaying it in a list). i will credit him in the readme, my mistake for not doing that before.
