### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [dkim0419/SoundRecorder#76]
Hi @dkim0419 

I found [this app ](https://play.google.com/store/apps/details?id=com.appwala.soundrecorder) on the Google Play Store. This guys just took the source code, added some ads and put it on the Google Play Store...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay), if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GPL3 and this guy is violating it by distributing the app without the source code;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning. (I watch him)

**Comment by Poussinou** [comment]
There is also [this one](https://play.google.com/store/apps/details?id=com.nikiizvorski.soundrecorderpro)

**Comment by Poussinou** [comment]
And also [this one](https://play.google.com/store/apps/details?id=com.jssmartapps.soundrecorder) and [this one](https://play.google.com/store/apps/details?id=com.ingic.easysoundrecorder)
Please take some time to report them all, if you want to do it ;)

**Comment by ghost** [comment]
@Poussinou 
the 1st app link shows item not found probably removed by google.

**Comment by dkim0419** [comment]
thanks for finding these. :)

**Comment by Poussinou** [comment]
@dkim0419 No problem :)
Did you reported them? :)

**Comment by Poussinou** [comment]
@dkim0419 Maybe also this [one](https://play.google.com/store/apps/details?id=com.mini.recorder) is a derivative work from your own app ?

**Comment by Poussinou** [comment]
There is another [here](https://play.google.com/store/apps/details?id=com.tan.soundrecorder) in all cases...

EDIT: And another one [here](https://play.google.com/store/apps/details?id=com.marcossitdev.recordsound.pro) !

**Comment by Poussinou** [comment]
And another one [here](https://play.google.com/store/apps/details?id=com.ndss.rgsoundrecorder)

**Comment by Poussinou** [comment]
One more [here](https://play.google.com/store/apps/details?id=com.juborajsarker.voicerecorder)...

**Comment by Poussinou** [comment]
Another one here : https://play.google.com/store/apps/details?id=com.audixo.soundrecorder

From [this developer](https://play.google.com/store/apps/developer?id=audixo)
